// Media scanner: checks images entering the viewport for AI signals and labels
// or blurs them. Two tiers, cheapest first:
//
//   1.5  contextual scan  — local, zero network. Looks at alt text, captions,
//        the src filename, and nearby links for AI-tool names / phrases. This
//        is an *inference* (a guess), so it only ever labels ("AI?"), softly.
//   2    provenance       — the worker reads C2PA / EXIF / XMP from the bytes.
//        This is *declared* AI, higher confidence: red "AI" badge, and it can
//        blur in Blur mode.
//
// Declared provenance wins over context when both fire. The heavy pixel model
// is never run here automatically — that's the right-click "Verify image" path.
(() => {
  const ns = (globalThis.AIBlocker = globalThis.AIBlocker || {});
  const MIN_SIZE = 128;
  const hostMatches = (host, patterns) =>
    patterns.some((p) => host === p || host.endsWith('.' + p));

  // Contextual signals — kept specific to avoid false positives. Bare words
  // like "ai" or "flux" are intentionally excluded.
  const CONTEXT_TERMS = [
    'midjourney', 'dall·e', 'dall-e', 'dalle', 'stable diffusion', 'stable-diffusion',
    'adobe firefly', 'ideogram', 'leonardo.ai', 'civitai', 'dreamstudio', 'nightcafe',
    'ai-generated', 'ai generated', 'generated by ai', 'made with ai', 'created with ai',
    'generated with ai', '#aiart', '#midjourney',
  ];
  const CONTEXT_HOSTS = [
    'midjourney.com', 'civitai.com', 'leonardo.ai', 'ideogram.ai', 'nightcafe.studio', 'stability.ai',
  ];
  // Sites that are *themselves* AI-image galleries — on these, treat every
  // content image as AI without per-image context work, and allow Blur mode to
  // act (the host is a strong enough signal).
  const AI_GALLERY_HOSTS = [
    'civitai.com', 'midjourney.com', 'leonardo.ai', 'ideogram.ai', 'nightcafe.studio',
    'openart.ai', 'prompthero.com', 'playground.com', 'tensor.art', 'lexica.art',
  ];

  const LABELS = {
    'ai-generated': { text: 'AI', title: 'AI-generated (declared in metadata)', ai: true },
    'ai-edited': { text: 'AI edited', title: 'Edited with generative AI (declared)', ai: true },
    'ai-software': { text: 'AI', title: 'Made with an AI image tool (metadata)', ai: true },
    'content-credentials': { text: 'CR', title: 'Has Content Credentials (C2PA)', ai: false },
    'ai-context': { text: 'AI?', title: 'Likely AI — inferred from page context', ai: true, inferred: true },
  };
  const DECLARED_AI = new Set(['ai-generated', 'ai-edited', 'ai-software']);

  class MediaScanner {
    constructor() {
      this.host = location.hostname;
      this.settings = null;
      this.io = null;
      this.mo = null;
      this.scanScheduled = false;
    }

    // --- lifecycle ---------------------------------------------------------

    start(settings) {
      this.settings = settings;
      this.galleryHost = AI_GALLERY_HOSTS.some((d) => hostMatches(this.host, [d]));
      ns.stats.media = 0;

      const off =
        !settings.enabled ||
        settings.mediaAction === 'off' ||
        hostMatches(this.host, settings.allowlist);
      if (off) {
        ns.reportStats();
        return;
      }

      this.injectStyle();
      this.io = new IntersectionObserver((e) => this.onIntersect(e), { rootMargin: '250px' });
      this.mo = new MutationObserver(() => this.scheduleScan());
      this.mo.observe(document.documentElement, { childList: true, subtree: true });

      if (document.body) this.scan();
      else document.addEventListener('DOMContentLoaded', () => this.scan(), { once: true });
      ns.reportStats();
    }

    stop() {
      this.io?.disconnect();
      this.io = null;
      this.mo?.disconnect();
      this.mo = null;
      document.querySelectorAll('.aiblock-media-wrap').forEach((w) => this.unwrap(w));
      document.querySelectorAll('[data-aiblock-media-seen]').forEach((img) =>
        img.removeAttribute('data-aiblock-media-seen')
      );
      ns.stats.media = 0;
    }

    // --- scanning ----------------------------------------------------------

    scheduleScan() {
      if (this.scanScheduled) return;
      this.scanScheduled = true;
      const run = () => {
        this.scanScheduled = false;
        this.scan();
      };
      if ('requestIdleCallback' in window) requestIdleCallback(run, { timeout: 400 });
      else setTimeout(run, 150);
    }

    scan() {
      if (!this.io) return;
      document.querySelectorAll('img:not([data-aiblock-media-seen])').forEach((img) => {
        img.dataset.aiblockMediaSeen = '1';
        this.io.observe(img);
      });
    }

    onIntersect(entries) {
      for (const e of entries) {
        if (!e.isIntersecting) continue;
        const img = e.target;
        this.io.unobserve(img);
        const rect = img.getBoundingClientRect();
        if (Math.max(rect.width, img.naturalWidth || 0) < MIN_SIZE) continue;

        // On an AI-gallery host every content image is AI; elsewhere, scan.
        const ctx = this.galleryHost ? 'ai-context' : this.contextScan(img);
        const url = img.currentSrc || img.src;
        if (url && /^https?:|^data:/.test(url)) this.check(img, url, ctx); // tier 2 needs bytes
        else if (ctx) this.apply(img, ctx, 'page context'); // blob:/unknown — context only
      }
    }

    // tier 1.5 — inspect text and links around the image
    contextScan(img) {
      const bits = [img.alt || '', img.title || '', img.getAttribute('aria-label') || ''];
      try {
        bits.push(decodeURIComponent(new URL(img.currentSrc || img.src, location.href).pathname));
      } catch {
        /* non-URL src */
      }
      const fig = img.closest('figure');
      if (fig) {
        const cap = fig.querySelector('figcaption');
        if (cap) bits.push(cap.textContent || '');
      }
      const parent = img.parentElement;
      if (parent) bits.push((parent.textContent || '').slice(0, 300));

      const hay = bits.join(' \n ').toLowerCase();
      if (CONTEXT_TERMS.some((t) => hay.includes(t))) return 'ai-context';

      // Links to AI hosts — both the anchor that *wraps* the image (galleries
      // like civitai/pinterest nest the img inside an <a>) and any descendant.
      const links = [img.closest('a[href]'), ...img.closest('figure, article, li, div, a')?.querySelectorAll?.('a[href]') ?? []];
      for (const a of links.slice(0, 30)) {
        if (!a) continue;
        let h;
        try {
          h = new URL(a.href).hostname.replace(/^www\./, '');
        } catch {
          continue;
        }
        if (CONTEXT_HOSTS.some((d) => h === d || h.endsWith('.' + d))) return 'ai-context';
      }
      return null;
    }

    // tier 2 — ask the worker for declared provenance, fall back to context
    check(img, url, ctx) {
      try {
        chrome.runtime.sendMessage({ type: ns.MSG.CHECK_IMAGE, url }, (res) => {
          if (chrome.runtime.lastError || !res) {
            if (ctx) this.apply(img, ctx, 'page context');
            return;
          }
          const v = res.verdict;
          if (DECLARED_AI.has(v)) this.apply(img, v, res.source);
          else if (ctx) this.apply(img, ctx, 'page context');
          else if (v === 'content-credentials') this.apply(img, v, res.source);
        });
      } catch {
        if (ctx) this.apply(img, ctx, 'page context');
      }
    }

    // --- actions -----------------------------------------------------------

    apply(img, verdict, source) {
      const info = LABELS[verdict];
      if (!info || img.dataset.aiblockMedia || !img.parentNode) return;
      img.dataset.aiblockMedia = verdict;

      const wrap = this.wrap(img);
      if (!wrap) return;

      const badge = document.createElement('span');
      const cls = info.inferred ? 'aiblock-maybe' : info.ai ? 'aiblock-ai' : 'aiblock-cr';
      badge.className = 'aiblock-media-badge ' + cls;
      badge.textContent = info.text;
      badge.title = source ? `${info.title} — ${source}` : info.title;
      wrap.appendChild(badge);

      // Declared AI blurs; inferred context-hits are label-only — except on an
      // AI-gallery host, where the host itself is a strong enough signal.
      if (info.ai && (!info.inferred || this.galleryHost) && this.settings.mediaAction === 'blur') {
        img.style.filter = 'blur(14px)';
        img.style.cursor = 'pointer';
        badge.textContent = 'AI · show';
        badge.style.pointerEvents = 'none';
        wrap.addEventListener(
          'click',
          (ev) => {
            ev.preventDefault();
            ev.stopPropagation();
            img.style.filter = '';
            badge.classList.add('aiblock-revealed');
          },
          { once: true, capture: true }
        );
      }

      if (info.ai) {
        ns.stats.media++;
        ns.reportStats();
      }
    }

    // --- right-click "Verify image" result ---------------------------------

    verifyResult({ srcUrl, meta, ml }) {
      let text;
      let kind;
      if (meta?.verdict && meta.verdict !== 'none') {
        const map = {
          'ai-generated': 'Declared AI-generated',
          'ai-edited': 'Declared AI-edited',
          'ai-software': 'Made with an AI tool',
          'content-credentials': 'Has Content Credentials (C2PA)',
        };
        text = '✓ ' + (map[meta.verdict] || meta.verdict) + (meta.source ? ` · ${meta.source}` : '');
        kind = meta.verdict === 'content-credentials' ? 'cr' : 'ai';
      } else if (!ml || ml.stub) {
        text = 'No AI metadata found · pixel model not installed (stub)';
        kind = 'info';
      } else {
        const pct = Math.round((ml.score || 0) * 100);
        text = `Pixel check: ${pct}% likely AI`;
        kind = pct >= 50 ? 'ai' : 'info';
      }
      this.toast(text, kind);

      if (kind === 'ai') {
        const img = [...document.images].find((i) => (i.currentSrc || i.src) === srcUrl);
        if (img && !img.dataset.aiblockMedia) {
          const v = meta?.verdict && meta.verdict !== 'none' ? meta.verdict : 'ai-context';
          this.apply(img, v, meta?.source || 'verified');
        }
      }
    }

    toast(text, kind) {
      const bg = kind === 'ai' ? '#b91c1c' : kind === 'cr' ? '#0d9488' : '#1f2937';
      const t = document.createElement('div');
      t.className = 'aiblock-toast';
      t.textContent = text;
      t.style.cssText =
        'position:fixed;left:50%;bottom:18px;transform:translateX(-50%);' +
        'z-index:2147483647;max-width:90vw;font:13px/1.4 system-ui,sans-serif;color:#fff;' +
        `background:${bg};padding:9px 14px;border-radius:10px;box-shadow:0 2px 10px rgba(0,0,0,.3);`;
      (document.body || document.documentElement).appendChild(t);
      setTimeout(() => t.remove(), 6000);
    }

    // --- wrap / style helpers ----------------------------------------------

    wrap(img) {
      const parent = img.parentElement;
      if (parent && parent.classList.contains('aiblock-media-wrap')) return parent;
      if (!parent) return null;
      const w = document.createElement('span');
      w.className = 'aiblock-media-wrap';
      img.replaceWith(w);
      w.appendChild(img);
      return w;
    }

    unwrap(w) {
      const img = w.querySelector('img');
      if (img) {
        img.style.filter = '';
        img.style.cursor = '';
        delete img.dataset.aiblockMedia;
        w.replaceWith(img);
      } else {
        w.remove();
      }
    }

    injectStyle() {
      if (document.getElementById('aiblock-media-style')) return;
      const s = document.createElement('style');
      s.id = 'aiblock-media-style';
      s.textContent = `
        .aiblock-media-wrap{position:relative;display:inline-block;line-height:0;max-width:100%}
        .aiblock-media-badge{position:absolute;top:6px;left:6px;z-index:2147483646;
          font:600 11px/1 system-ui,sans-serif;letter-spacing:.02em;color:#fff;
          padding:3px 6px;border-radius:6px;box-shadow:0 1px 3px rgba(0,0,0,.35)}
        .aiblock-ai{background:#b91c1c}
        .aiblock-cr{background:#0d9488}
        .aiblock-maybe{background:#b45309}
        .aiblock-revealed{opacity:.55}
      `;
      (document.head || document.documentElement).appendChild(s);
    }
  }

  ns.MediaScanner = MediaScanner;
})();
